<?php

namespace Database\Seeders;

use App\Models\Pharmacy;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pharmacies = Pharmacy::where('status', 'approved')->get();

        if ($pharmacies->isEmpty()) {
            $this->command->warn('⚠️  No approved pharmacies found. Run PharmacySeeder first.');
            return;
        }

        $products = [
            // Médicaments
            [
                'name' => 'Paracétamol 500mg',
                'description' => 'Antalgique et antipyrétique. Traitement symptomatique des douleurs d\'intensité légère à modérée et/ou des états fébriles.',
                'category' => 'Médicaments',
                'brand' => 'Doliprane',
                'price' => 2500,
                'discount_price' => null,
                'stock_quantity' => rand(50, 200),
                'sku' => 'MED-PAR-500',
                'requires_prescription' => false,
                'unit' => 'boîte',
                'units_per_pack' => 20,
                'manufacturer' => 'Sanofi',
                'active_ingredient' => 'Paracétamol',
                'usage_instructions' => 'Adultes: 1 à 2 comprimés, 3 fois par jour. Enfants: selon le poids.',
                'side_effects' => 'Rares: réactions allergiques.',
                'is_featured' => true,
            ],
            [
                'name' => 'Ibuprofène 400mg',
                'description' => 'Anti-inflammatoire non stéroïdien (AINS). Traitement des douleurs et de la fièvre.',
                'category' => 'Médicaments',
                'brand' => 'Advil',
                'price' => 3500,
                'discount_price' => 3000,
                'stock_quantity' => rand(30, 150),
                'sku' => 'MED-IBU-400',
                'requires_prescription' => false,
                'unit' => 'boîte',
                'units_per_pack' => 20,
                'manufacturer' => 'Pfizer',
                'active_ingredient' => 'Ibuprofène',
                'usage_instructions' => '1 comprimé toutes les 6 heures, sans dépasser 3 comprimés par jour.',
                'side_effects' => 'Troubles digestifs, maux de tête.',
                'is_featured' => true,
            ],
            [
                'name' => 'Amoxicilline 1g',
                'description' => 'Antibiotique de la famille des pénicillines. Traitement des infections bactériennes.',
                'category' => 'Médicaments',
                'brand' => 'Clamoxyl',
                'price' => 8500,
                'discount_price' => null,
                'stock_quantity' => rand(20, 100),
                'sku' => 'MED-AMO-1000',
                'requires_prescription' => true,
                'unit' => 'boîte',
                'units_per_pack' => 14,
                'manufacturer' => 'GlaxoSmithKline',
                'active_ingredient' => 'Amoxicilline',
                'usage_instructions' => '1g matin et soir pendant 7 jours.',
                'side_effects' => 'Diarrhée, nausées, réactions allergiques.',
                'is_featured' => false,
            ],
            [
                'name' => 'Aspirine 100mg',
                'description' => 'Antiagrégant plaquettaire. Prévention des maladies cardiovasculaires.',
                'category' => 'Médicaments',
                'brand' => 'Kardégic',
                'price' => 4500,
                'discount_price' => 4000,
                'stock_quantity' => rand(40, 120),
                'sku' => 'MED-ASP-100',
                'requires_prescription' => true,
                'unit' => 'boîte',
                'units_per_pack' => 30,
                'manufacturer' => 'Sanofi',
                'active_ingredient' => 'Acide acétylsalicylique',
                'usage_instructions' => '1 sachet par jour à dissoudre dans un verre d\'eau.',
                'side_effects' => 'Troubles digestifs, risque hémorragique.',
                'is_featured' => false,
            ],
            [
                'name' => 'Oméprazole 20mg',
                'description' => 'Inhibiteur de la pompe à protons. Traitement des ulcères et du reflux gastro-œsophagien.',
                'category' => 'Médicaments',
                'brand' => 'Mopral',
                'price' => 6500,
                'discount_price' => null,
                'stock_quantity' => rand(25, 100),
                'sku' => 'MED-OME-20',
                'requires_prescription' => true,
                'unit' => 'boîte',
                'units_per_pack' => 28,
                'manufacturer' => 'AstraZeneca',
                'active_ingredient' => 'Oméprazole',
                'usage_instructions' => '1 gélule le matin à jeun.',
                'side_effects' => 'Maux de tête, troubles digestifs.',
                'is_featured' => false,
            ],

            // Compléments Alimentaires
            [
                'name' => 'Vitamine C 1000mg',
                'description' => 'Complément alimentaire. Renforce le système immunitaire et réduit la fatigue.',
                'category' => 'Compléments Alimentaires',
                'brand' => 'Vitascorbol',
                'price' => 5500,
                'discount_price' => 5000,
                'stock_quantity' => rand(60, 200),
                'sku' => 'COMP-VIT-C-1000',
                'requires_prescription' => false,
                'unit' => 'boîte',
                'units_per_pack' => 30,
                'manufacturer' => 'Bayer',
                'active_ingredient' => 'Acide ascorbique',
                'usage_instructions' => '1 comprimé par jour.',
                'side_effects' => 'Troubles digestifs à forte dose.',
                'is_featured' => true,
            ],
            [
                'name' => 'Multivitamines',
                'description' => 'Complément multivitaminé. Couvre les besoins quotidiens en vitamines et minéraux.',
                'category' => 'Compléments Alimentaires',
                'brand' => 'Centrum',
                'price' => 12000,
                'discount_price' => 10000,
                'stock_quantity' => rand(40, 150),
                'sku' => 'COMP-MULTI',
                'requires_prescription' => false,
                'unit' => 'boîte',
                'units_per_pack' => 30,
                'manufacturer' => 'Pfizer',
                'active_ingredient' => 'Complexe multivitaminé',
                'usage_instructions' => '1 comprimé par jour au cours d\'un repas.',
                'side_effects' => 'Généralement bien toléré.',
                'is_featured' => true,
            ],
            [
                'name' => 'Oméga 3',
                'description' => 'Acides gras essentiels. Soutient la santé cardiovasculaire et cérébrale.',
                'category' => 'Compléments Alimentaires',
                'brand' => 'Omega Pharma',
                'price' => 15000,
                'discount_price' => null,
                'stock_quantity' => rand(30, 100),
                'sku' => 'COMP-OME-3',
                'requires_prescription' => false,
                'unit' => 'boîte',
                'units_per_pack' => 60,
                'manufacturer' => 'Pharma Nord',
                'active_ingredient' => 'EPA et DHA',
                'usage_instructions' => '2 capsules par jour pendant les repas.',
                'side_effects' => 'Troubles digestifs légers.',
                'is_featured' => false,
            ],

            // Matériel Médical
            [
                'name' => 'Thermomètre Digital',
                'description' => 'Thermomètre électronique pour mesure de température corporelle rapide et précise.',
                'category' => 'Matériel Médical',
                'brand' => 'Beurer',
                'price' => 8000,
                'discount_price' => 7000,
                'stock_quantity' => rand(20, 80),
                'sku' => 'MAT-THER-DIG',
                'requires_prescription' => false,
                'unit' => 'pièce',
                'units_per_pack' => 1,
                'manufacturer' => 'Beurer GmbH',
                'active_ingredient' => null,
                'usage_instructions' => 'Placer sous la langue, sous l\'aisselle ou dans le rectum selon les instructions.',
                'side_effects' => null,
                'is_featured' => true,
            ],
            [
                'name' => 'Tensiomètre Automatique',
                'description' => 'Appareil de mesure de tension artérielle au bras avec affichage digital.',
                'category' => 'Matériel Médical',
                'brand' => 'Omron',
                'price' => 35000,
                'discount_price' => 30000,
                'stock_quantity' => rand(10, 50),
                'sku' => 'MAT-TENS-AUTO',
                'requires_prescription' => false,
                'unit' => 'pièce',
                'units_per_pack' => 1,
                'manufacturer' => 'Omron Healthcare',
                'active_ingredient' => null,
                'usage_instructions' => 'S\'asseoir, placer le brassard au niveau du cœur et appuyer sur le bouton.',
                'side_effects' => null,
                'is_featured' => true,
            ],
            [
                'name' => 'Masques Chirurgicaux',
                'description' => 'Masques de protection à usage unique. Filtration bactérienne > 95%.',
                'category' => 'Matériel Médical',
                'brand' => 'MediMask',
                'price' => 10000,
                'discount_price' => 8500,
                'stock_quantity' => rand(100, 500),
                'sku' => 'MAT-MASQ-CHIR',
                'requires_prescription' => false,
                'unit' => 'boîte',
                'units_per_pack' => 50,
                'manufacturer' => 'Various',
                'active_ingredient' => null,
                'usage_instructions' => 'Couvrir le nez et la bouche. À usage unique.',
                'side_effects' => null,
                'is_featured' => false,
            ],

            // Hygiène & Beauté
            [
                'name' => 'Gel Hydroalcoolique 500ml',
                'description' => 'Solution désinfectante pour les mains sans rinçage. Élimine 99,9% des germes.',
                'category' => 'Hygiène & Beauté',
                'brand' => 'Sanytol',
                'price' => 4500,
                'discount_price' => 4000,
                'stock_quantity' => rand(80, 300),
                'sku' => 'HYG-GEL-500',
                'requires_prescription' => false,
                'unit' => 'flacon',
                'units_per_pack' => 1,
                'manufacturer' => 'Sanytol',
                'active_ingredient' => 'Alcool éthylique 70%',
                'usage_instructions' => 'Appliquer une noisette sur mains sèches et frotter jusqu\'à séchage complet.',
                'side_effects' => 'Peut assécher la peau.',
                'is_featured' => true,
            ],
            [
                'name' => 'Savon Antibactérien',
                'description' => 'Savon liquide pour les mains avec action antibactérienne.',
                'category' => 'Hygiène & Beauté',
                'brand' => 'Dettol',
                'price' => 3000,
                'discount_price' => null,
                'stock_quantity' => rand(60, 250),
                'sku' => 'HYG-SAV-ANTI',
                'requires_prescription' => false,
                'unit' => 'flacon',
                'units_per_pack' => 1,
                'manufacturer' => 'Reckitt Benckiser',
                'active_ingredient' => 'Chloroxylénol',
                'usage_instructions' => 'Mouiller les mains, appliquer le savon, frotter pendant 20 secondes et rincer.',
                'side_effects' => null,
                'is_featured' => false,
            ],

            // Premiers Soins
            [
                'name' => 'Pansements Assortis',
                'description' => 'Boîte de pansements stériles de différentes tailles pour petites plaies.',
                'category' => 'Premiers Soins',
                'brand' => 'Hansaplast',
                'price' => 2500,
                'discount_price' => null,
                'stock_quantity' => rand(100, 400),
                'sku' => 'PREM-PANS-ASS',
                'requires_prescription' => false,
                'unit' => 'boîte',
                'units_per_pack' => 20,
                'manufacturer' => 'Beiersdorf',
                'active_ingredient' => null,
                'usage_instructions' => 'Nettoyer la plaie, sécher et appliquer le pansement.',
                'side_effects' => null,
                'is_featured' => false,
            ],
            [
                'name' => 'Désinfectant Plaies',
                'description' => 'Solution antiseptique pour nettoyer et désinfecter les plaies superficielles.',
                'category' => 'Premiers Soins',
                'brand' => 'Bétadine',
                'price' => 5000,
                'discount_price' => 4500,
                'stock_quantity' => rand(40, 150),
                'sku' => 'PREM-DES-PLAIE',
                'requires_prescription' => false,
                'unit' => 'flacon',
                'units_per_pack' => 1,
                'manufacturer' => 'Meda Pharma',
                'active_ingredient' => 'Povidone iodée',
                'usage_instructions' => 'Appliquer sur la plaie propre avec une compresse stérile.',
                'side_effects' => 'Allergie à l\'iode rare.',
                'is_featured' => false,
            ],
        ];

        $createdCount = 0;
        foreach ($pharmacies as $pharmacy) {
            // Each pharmacy gets a random selection of products
            $selectedProducts = collect($products)->random(min(rand(10, 15), count($products)));
            
            foreach ($selectedProducts as $productData) {
                Product::create([
                    'pharmacy_id' => $pharmacy->id,
                    'name' => $productData['name'],
                    'description' => $productData['description'],
                    'category' => $productData['category'],
                    'brand' => $productData['brand'],
                    'price' => $productData['price'],
                    'discount_price' => $productData['discount_price'],
                    'stock_quantity' => $productData['stock_quantity'],
                    'low_stock_threshold' => 10,
                    'sku' => $productData['sku'] . '-' . $pharmacy->id,
                    'requires_prescription' => $productData['requires_prescription'],
                    'is_available' => true,
                    'is_featured' => $productData['is_featured'],
                    'unit' => $productData['unit'],
                    'units_per_pack' => $productData['units_per_pack'],
                    'manufacturer' => $productData['manufacturer'],
                    'active_ingredient' => $productData['active_ingredient'],
                    'usage_instructions' => $productData['usage_instructions'],
                    'side_effects' => $productData['side_effects'],
                    'expiry_date' => now()->addYears(rand(1, 3)),
                ]);
                $createdCount++;
            }
        }

        $this->command->info("✅ Created {$createdCount} products across {$pharmacies->count()} pharmacies");
    }
}

