// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/auth/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i4;
import 'package:drpharma_client/core/network/api_client.dart' as _i8;
import 'package:drpharma_client/features/auth/data/datasources/auth_local_datasource.dart'
    as _i7;
import 'package:drpharma_client/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i5;
import 'package:drpharma_client/features/auth/data/models/auth_response_model.dart'
    as _i2;
import 'package:drpharma_client/features/auth/data/models/user_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResponseModel_0 extends _i1.SmartFake
    implements _i2.AuthResponseModel {
  _FakeAuthResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOptions_2 extends _i1.SmartFake implements _i4.Options {
  _FakeOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3<T> extends _i1.SmartFake implements _i4.Response<T> {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i5.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AuthResponseModel> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i6.Future<_i2.AuthResponseModel>.value(
              _FakeAuthResponseModel_0(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.AuthResponseModel>);

  @override
  _i6.Future<_i2.AuthResponseModel> register({
    required String? name,
    required String? email,
    required String? phone,
    required String? password,
    String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #phone: phone,
              #password: password,
              #address: address,
            }),
            returnValue: _i6.Future<_i2.AuthResponseModel>.value(
              _FakeAuthResponseModel_0(
                this,
                Invocation.method(#register, [], {
                  #name: name,
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #address: address,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.AuthResponseModel>);

  @override
  _i6.Future<void> logout(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.UserModel> getCurrentUser(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, [token]),
            returnValue: _i6.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#getCurrentUser, [token]),
              ),
            ),
          )
          as _i6.Future<_i3.UserModel>);

  @override
  _i6.Future<void> updatePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.AuthResponseModel> verifyOtp({
    required String? identifier,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {
              #identifier: identifier,
              #otp: otp,
            }),
            returnValue: _i6.Future<_i2.AuthResponseModel>.value(
              _FakeAuthResponseModel_0(
                this,
                Invocation.method(#verifyOtp, [], {
                  #identifier: identifier,
                  #otp: otp,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.AuthResponseModel>);

  @override
  _i6.Future<_i2.AuthResponseModel> verifyFirebaseOtp({
    required String? phone,
    required String? firebaseUid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyFirebaseOtp, [], {
              #phone: phone,
              #firebaseUid: firebaseUid,
            }),
            returnValue: _i6.Future<_i2.AuthResponseModel>.value(
              _FakeAuthResponseModel_0(
                this,
                Invocation.method(#verifyFirebaseOtp, [], {
                  #phone: phone,
                  #firebaseUid: firebaseUid,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.AuthResponseModel>);

  @override
  _i6.Future<Map<String, dynamic>> resendOtp({required String? identifier}) =>
      (super.noSuchMethod(
            Invocation.method(#resendOtp, [], {#identifier: identifier}),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> forgotPassword({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [], {#email: email}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i7.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> cacheToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#cacheToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getCachedToken() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cacheUser(_i3.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUser, [user]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.UserModel?> getCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUser, []),
            returnValue: _i6.Future<_i3.UserModel?>.value(),
          )
          as _i6.Future<_i3.UserModel?>);

  @override
  _i6.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i8.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasToken =>
      (super.noSuchMethod(Invocation.getter(#hasToken), returnValue: false)
          as bool);

  @override
  void setToken(String? token) => super.noSuchMethod(
    Invocation.method(#setToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void clearToken() => super.noSuchMethod(
    Invocation.method(#clearToken, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Options authorizedOptions(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#authorizedOptions, [token]),
            returnValue: _FakeOptions_2(
              this,
              Invocation.method(#authorizedOptions, [token]),
            ),
          )
          as _i4.Options);

  @override
  _i6.Future<_i4.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters, #options: options},
            ),
            returnValue: _i6.Future<_i4.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters, #options: options},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<dynamic>>);

  @override
  _i6.Future<_i4.Response<dynamic>> post(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
              },
            ),
            returnValue: _i6.Future<_i4.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<dynamic>>);

  @override
  _i6.Future<_i4.Response<dynamic>> put(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
              },
            ),
            returnValue: _i6.Future<_i4.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<dynamic>>);

  @override
  _i6.Future<_i4.Response<dynamic>> delete(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {#queryParameters: queryParameters, #options: options},
            ),
            returnValue: _i6.Future<_i4.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {#queryParameters: queryParameters, #options: options},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<dynamic>>);

  @override
  _i6.Future<_i4.Response<dynamic>> uploadMultipart(
    String? path, {
    required _i4.FormData? formData,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.ProgressCallback? onSendProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadMultipart,
              [path],
              {
                #formData: formData,
                #queryParameters: queryParameters,
                #options: options,
                #onSendProgress: onSendProgress,
              },
            ),
            returnValue: _i6.Future<_i4.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #uploadMultipart,
                  [path],
                  {
                    #formData: formData,
                    #queryParameters: queryParameters,
                    #options: options,
                    #onSendProgress: onSendProgress,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<dynamic>>);
}
