// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/prescriptions/presentation/providers/prescriptions_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i13;
import 'dart:typed_data' as _i14;

import 'package:dartz/dartz.dart' as _i3;
import 'package:drpharma_client/core/errors/failures.dart' as _i6;
import 'package:drpharma_client/features/prescriptions/domain/entities/prescription_entity.dart'
    as _i7;
import 'package:drpharma_client/features/prescriptions/domain/repositories/prescriptions_repository.dart'
    as _i2;
import 'package:drpharma_client/features/prescriptions/domain/usecases/get_prescription_details_usecase.dart'
    as _i10;
import 'package:drpharma_client/features/prescriptions/domain/usecases/get_prescriptions_usecase.dart'
    as _i9;
import 'package:drpharma_client/features/prescriptions/domain/usecases/pay_prescription_usecase.dart'
    as _i11;
import 'package:drpharma_client/features/prescriptions/domain/usecases/upload_prescription_usecase.dart'
    as _i4;
import 'package:image_picker/image_picker.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePrescriptionsRepository_0 extends _i1.SmartFake
    implements _i2.PrescriptionsRepository {
  _FakePrescriptionsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UploadPrescriptionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadPrescriptionUseCase extends _i1.Mock
    implements _i4.UploadPrescriptionUseCase {
  MockUploadPrescriptionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PrescriptionsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePrescriptionsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PrescriptionsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.PrescriptionEntity>> call({
    required List<_i8.XFile>? images,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#images: images, #notes: notes}),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, _i7.PrescriptionEntity>
                >.value(
                  _FakeEither_1<_i6.Failure, _i7.PrescriptionEntity>(
                    this,
                    Invocation.method(#call, [], {
                      #images: images,
                      #notes: notes,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.PrescriptionEntity>>);
}

/// A class which mocks [GetPrescriptionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPrescriptionsUseCase extends _i1.Mock
    implements _i9.GetPrescriptionsUseCase {
  MockGetPrescriptionsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PrescriptionsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePrescriptionsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PrescriptionsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.PrescriptionEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, List<_i7.PrescriptionEntity>>
                >.value(
                  _FakeEither_1<_i6.Failure, List<_i7.PrescriptionEntity>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.PrescriptionEntity>>>);
}

/// A class which mocks [GetPrescriptionDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPrescriptionDetailsUseCase extends _i1.Mock
    implements _i10.GetPrescriptionDetailsUseCase {
  MockGetPrescriptionDetailsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PrescriptionsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePrescriptionsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PrescriptionsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.PrescriptionEntity>> call(
    int? prescriptionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [prescriptionId]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, _i7.PrescriptionEntity>
                >.value(
                  _FakeEither_1<_i6.Failure, _i7.PrescriptionEntity>(
                    this,
                    Invocation.method(#call, [prescriptionId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.PrescriptionEntity>>);
}

/// A class which mocks [PayPrescriptionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPayPrescriptionUseCase extends _i1.Mock
    implements _i11.PayPrescriptionUseCase {
  MockPayPrescriptionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PrescriptionsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePrescriptionsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PrescriptionsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, Map<String, dynamic>>> call({
    required int? prescriptionId,
    required String? paymentMethod,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #prescriptionId: prescriptionId,
              #paymentMethod: paymentMethod,
            }),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_1<_i6.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#call, [], {
                      #prescriptionId: prescriptionId,
                      #paymentMethod: paymentMethod,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, Map<String, dynamic>>>);
}

/// A class which mocks [XFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockXFile extends _i1.Mock implements _i8.XFile {
  MockXFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i5.Future<void> saveTo(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#saveTo, [path]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<String> readAsString({
    _i13.Encoding? encoding = const _i13.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i5.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i14.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i5.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
          )
          as _i5.Future<_i14.Uint8List>);

  @override
  _i5.Stream<_i14.Uint8List> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i5.Stream<_i14.Uint8List>.empty(),
          )
          as _i5.Stream<_i14.Uint8List>);

  @override
  _i5.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i5.Future<DateTime>.value(
              _FakeDateTime_2(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i5.Future<DateTime>);
}
