// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/pharmacies/presentation/providers/pharmacies_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:drpharma_client/core/errors/failures.dart' as _i5;
import 'package:drpharma_client/features/pharmacies/domain/entities/pharmacy_entity.dart'
    as _i6;
import 'package:drpharma_client/features/pharmacies/domain/repositories/pharmacies_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PharmaciesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPharmaciesRepository extends _i1.Mock
    implements _i3.PharmaciesRepository {
  MockPharmaciesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>> getPharmacies({
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPharmacies, [], {
              #page: page,
              #perPage: perPage,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PharmacyEntity>>(
                    this,
                    Invocation.method(#getPharmacies, [], {
                      #page: page,
                      #perPage: perPage,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>>
  getNearbyPharmacies({
    required double? latitude,
    required double? longitude,
    double? radius = 10.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyPharmacies, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radius: radius,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PharmacyEntity>>(
                    this,
                    Invocation.method(#getNearbyPharmacies, [], {
                      #latitude: latitude,
                      #longitude: longitude,
                      #radius: radius,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>>
  getOnDutyPharmacies({double? latitude, double? longitude, double? radius}) =>
      (super.noSuchMethod(
            Invocation.method(#getOnDutyPharmacies, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radius: radius,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PharmacyEntity>>(
                    this,
                    Invocation.method(#getOnDutyPharmacies, [], {
                      #latitude: latitude,
                      #longitude: longitude,
                      #radius: radius,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>>
  getFeaturedPharmacies() =>
      (super.noSuchMethod(
            Invocation.method(#getFeaturedPharmacies, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PharmacyEntity>>(
                    this,
                    Invocation.method(#getFeaturedPharmacies, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PharmacyEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PharmacyEntity>> getPharmacyDetails(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPharmacyDetails, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PharmacyEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.PharmacyEntity>(
                    this,
                    Invocation.method(#getPharmacyDetails, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PharmacyEntity>>);
}
