// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/profile/presentation/providers/profile_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i11;

import 'package:dartz/dartz.dart' as _i3;
import 'package:drpharma_client/core/errors/failures.dart' as _i6;
import 'package:drpharma_client/features/profile/domain/entities/profile_entity.dart'
    as _i7;
import 'package:drpharma_client/features/profile/domain/entities/update_profile_entity.dart'
    as _i9;
import 'package:drpharma_client/features/profile/domain/repositories/profile_repository.dart'
    as _i2;
import 'package:drpharma_client/features/profile/domain/usecases/delete_avatar_usecase.dart'
    as _i12;
import 'package:drpharma_client/features/profile/domain/usecases/get_profile_usecase.dart'
    as _i4;
import 'package:drpharma_client/features/profile/domain/usecases/update_profile_usecase.dart'
    as _i8;
import 'package:drpharma_client/features/profile/domain/usecases/upload_avatar_usecase.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileRepository_0 extends _i1.SmartFake
    implements _i2.ProfileRepository {
  _FakeProfileRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUseCase extends _i1.Mock implements _i4.GetProfileUseCase {
  MockGetProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProfileRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ProfileEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.ProfileEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.ProfileEntity>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.ProfileEntity>>);
}

/// A class which mocks [UpdateProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileUseCase extends _i1.Mock
    implements _i8.UpdateProfileUseCase {
  MockUpdateProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProfileRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ProfileEntity>> call(
    _i9.UpdateProfileEntity? updateProfile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [updateProfile]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.ProfileEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.ProfileEntity>(
                    this,
                    Invocation.method(#call, [updateProfile]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.ProfileEntity>>);
}

/// A class which mocks [UploadAvatarUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadAvatarUseCase extends _i1.Mock
    implements _i10.UploadAvatarUseCase {
  MockUploadAvatarUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProfileRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call(
    _i11.Uint8List? imageBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [imageBytes]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#call, [imageBytes]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [DeleteAvatarUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAvatarUseCase extends _i1.Mock
    implements _i12.DeleteAvatarUseCase {
  MockDeleteAvatarUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProfileRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
