// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/profile/domain/usecases/profile_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i8;

import 'package:dartz/dartz.dart' as _i2;
import 'package:drpharma_client/core/errors/failures.dart' as _i5;
import 'package:drpharma_client/features/profile/domain/entities/profile_entity.dart'
    as _i6;
import 'package:drpharma_client/features/profile/domain/entities/update_profile_entity.dart'
    as _i7;
import 'package:drpharma_client/features/profile/domain/repositories/profile_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ProfileEntity>(
                    this,
                    Invocation.method(#getProfile, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>> updateProfile(
    _i7.UpdateProfileEntity? updateProfile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [updateProfile]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ProfileEntity>(
                    this,
                    Invocation.method(#updateProfile, [updateProfile]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> uploadAvatar(
    _i8.Uint8List? imageBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAvatar, [imageBytes]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#uploadAvatar, [imageBytes]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteAvatar() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAvatar, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteAvatar, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
