// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/addresses/presentation/providers/addresses_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:drpharma_client/core/errors/failures.dart' as _i5;
import 'package:drpharma_client/features/addresses/domain/entities/address_entity.dart'
    as _i6;
import 'package:drpharma_client/features/addresses/domain/repositories/address_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AddressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressRepository extends _i1.Mock implements _i3.AddressRepository {
  MockAddressRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AddressEntity>>> getAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAddresses, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.AddressEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AddressEntity>>(
                    this,
                    Invocation.method(#getAddresses, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AddressEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>> getAddress(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAddress, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AddressEntity>(
                    this,
                    Invocation.method(#getAddress, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>> getDefaultAddress() =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultAddress, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AddressEntity>(
                    this,
                    Invocation.method(#getDefaultAddress, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>> createAddress({
    required String? label,
    required String? address,
    String? city,
    String? district,
    String? phone,
    String? instructions,
    double? latitude,
    double? longitude,
    bool? isDefault = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAddress, [], {
              #label: label,
              #address: address,
              #city: city,
              #district: district,
              #phone: phone,
              #instructions: instructions,
              #latitude: latitude,
              #longitude: longitude,
              #isDefault: isDefault,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AddressEntity>(
                    this,
                    Invocation.method(#createAddress, [], {
                      #label: label,
                      #address: address,
                      #city: city,
                      #district: district,
                      #phone: phone,
                      #instructions: instructions,
                      #latitude: latitude,
                      #longitude: longitude,
                      #isDefault: isDefault,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>> updateAddress({
    required int? id,
    String? label,
    String? address,
    String? city,
    String? district,
    String? phone,
    String? instructions,
    double? latitude,
    double? longitude,
    bool? isDefault,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddress, [], {
              #id: id,
              #label: label,
              #address: address,
              #city: city,
              #district: district,
              #phone: phone,
              #instructions: instructions,
              #latitude: latitude,
              #longitude: longitude,
              #isDefault: isDefault,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AddressEntity>(
                    this,
                    Invocation.method(#updateAddress, [], {
                      #id: id,
                      #label: label,
                      #address: address,
                      #city: city,
                      #district: district,
                      #phone: phone,
                      #instructions: instructions,
                      #latitude: latitude,
                      #longitude: longitude,
                      #isDefault: isDefault,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteAddress(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteAddress, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>> setDefaultAddress(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultAddress, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AddressEntity>(
                    this,
                    Invocation.method(#setDefaultAddress, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AddressEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.AddressFormData>> getLabels() =>
      (super.noSuchMethod(
            Invocation.method(#getLabels, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i3.AddressFormData>>.value(
                  _FakeEither_0<_i5.Failure, _i3.AddressFormData>(
                    this,
                    Invocation.method(#getLabels, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i3.AddressFormData>>);
}
