// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/prescriptions/domain/usecases/prescriptions_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:drpharma_client/core/errors/failures.dart' as _i5;
import 'package:drpharma_client/features/prescriptions/domain/entities/prescription_entity.dart'
    as _i6;
import 'package:drpharma_client/features/prescriptions/domain/repositories/prescriptions_repository.dart'
    as _i3;
import 'package:image_picker/image_picker.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PrescriptionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrescriptionsRepository extends _i1.Mock
    implements _i3.PrescriptionsRepository {
  MockPrescriptionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PrescriptionEntity>>
  uploadPrescription({required List<_i7.XFile>? images, String? notes}) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPrescription, [], {
              #images: images,
              #notes: notes,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.PrescriptionEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.PrescriptionEntity>(
                    this,
                    Invocation.method(#uploadPrescription, [], {
                      #images: images,
                      #notes: notes,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PrescriptionEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PrescriptionEntity>>>
  getPrescriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getPrescriptions, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PrescriptionEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PrescriptionEntity>>(
                    this,
                    Invocation.method(#getPrescriptions, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PrescriptionEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PrescriptionEntity>>
  getPrescriptionDetails(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPrescriptionDetails, [id]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.PrescriptionEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.PrescriptionEntity>(
                    this,
                    Invocation.method(#getPrescriptionDetails, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PrescriptionEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> payPrescription({
    required int? prescriptionId,
    required String? paymentMethod,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#payPrescription, [], {
              #prescriptionId: prescriptionId,
              #paymentMethod: paymentMethod,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#payPrescription, [], {
                      #prescriptionId: prescriptionId,
                      #paymentMethod: paymentMethod,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
}
