// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/orders/domain/usecases/cancel_order_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:drpharma_client/core/errors/failures.dart' as _i5;
import 'package:drpharma_client/features/orders/domain/entities/delivery_address_entity.dart'
    as _i8;
import 'package:drpharma_client/features/orders/domain/entities/order_entity.dart'
    as _i6;
import 'package:drpharma_client/features/orders/domain/entities/order_item_entity.dart'
    as _i7;
import 'package:drpharma_client/features/orders/domain/repositories/orders_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrdersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersRepository extends _i1.Mock implements _i3.OrdersRepository {
  MockOrdersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.OrderEntity>>> getOrders({
    String? status,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, [], {
              #status: status,
              #page: page,
              #perPage: perPage,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.OrderEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.OrderEntity>>(
                    this,
                    Invocation.method(#getOrders, [], {
                      #status: status,
                      #page: page,
                      #perPage: perPage,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.OrderEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.OrderEntity>> getOrderDetails(
    int? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderDetails, [orderId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.OrderEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.OrderEntity>(
                    this,
                    Invocation.method(#getOrderDetails, [orderId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.OrderEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.OrderEntity>> createOrder({
    required int? pharmacyId,
    required List<_i7.OrderItemEntity>? items,
    required _i8.DeliveryAddressEntity? deliveryAddress,
    required String? paymentMode,
    String? prescriptionImage,
    String? customerNotes,
    int? prescriptionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #pharmacyId: pharmacyId,
              #items: items,
              #deliveryAddress: deliveryAddress,
              #paymentMode: paymentMode,
              #prescriptionImage: prescriptionImage,
              #customerNotes: customerNotes,
              #prescriptionId: prescriptionId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.OrderEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.OrderEntity>(
                    this,
                    Invocation.method(#createOrder, [], {
                      #pharmacyId: pharmacyId,
                      #items: items,
                      #deliveryAddress: deliveryAddress,
                      #paymentMode: paymentMode,
                      #prescriptionImage: prescriptionImage,
                      #customerNotes: customerNotes,
                      #prescriptionId: prescriptionId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.OrderEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> cancelOrder(
    int? orderId,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [orderId, reason]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#cancelOrder, [orderId, reason]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> initiatePayment({
    required int? orderId,
    required String? provider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initiatePayment, [], {
              #orderId: orderId,
              #provider: provider,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#initiatePayment, [], {
                      #orderId: orderId,
                      #provider: provider,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getTrackingInfo(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackingInfo, [orderId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);
}
