// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/orders/data/repositories/orders_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:drpharma_client/core/network/api_client.dart' as _i2;
import 'package:drpharma_client/features/orders/data/datasources/orders_local_datasource.dart'
    as _i8;
import 'package:drpharma_client/features/orders/data/datasources/orders_remote_datasource.dart'
    as _i5;
import 'package:drpharma_client/features/orders/data/models/order_item_model.dart'
    as _i7;
import 'package:drpharma_client/features/orders/data/models/order_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderModel_1 extends _i1.SmartFake implements _i3.OrderModel {
  _FakeOrderModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_2 extends _i1.SmartFake
    implements _i4.SharedPreferences {
  _FakeSharedPreferences_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrdersRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersRemoteDataSource extends _i1.Mock
    implements _i5.OrdersRemoteDataSource {
  MockOrdersRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i6.Future<List<_i3.OrderModel>> getOrders({
    String? status,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, [], {
              #status: status,
              #page: page,
              #perPage: perPage,
            }),
            returnValue: _i6.Future<List<_i3.OrderModel>>.value(
              <_i3.OrderModel>[],
            ),
          )
          as _i6.Future<List<_i3.OrderModel>>);

  @override
  _i6.Future<_i3.OrderModel> getOrderDetails(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderDetails, [orderId]),
            returnValue: _i6.Future<_i3.OrderModel>.value(
              _FakeOrderModel_1(
                this,
                Invocation.method(#getOrderDetails, [orderId]),
              ),
            ),
          )
          as _i6.Future<_i3.OrderModel>);

  @override
  _i6.Future<_i3.OrderModel> createOrder({
    required int? pharmacyId,
    required List<_i7.OrderItemModel>? items,
    required Map<String, dynamic>? deliveryAddress,
    required String? paymentMode,
    String? prescriptionImage,
    String? customerNotes,
    int? prescriptionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #pharmacyId: pharmacyId,
              #items: items,
              #deliveryAddress: deliveryAddress,
              #paymentMode: paymentMode,
              #prescriptionImage: prescriptionImage,
              #customerNotes: customerNotes,
              #prescriptionId: prescriptionId,
            }),
            returnValue: _i6.Future<_i3.OrderModel>.value(
              _FakeOrderModel_1(
                this,
                Invocation.method(#createOrder, [], {
                  #pharmacyId: pharmacyId,
                  #items: items,
                  #deliveryAddress: deliveryAddress,
                  #paymentMode: paymentMode,
                  #prescriptionImage: prescriptionImage,
                  #customerNotes: customerNotes,
                  #prescriptionId: prescriptionId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.OrderModel>);

  @override
  _i6.Future<void> cancelOrder(int? orderId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [orderId, reason]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> initiatePayment({
    required int? orderId,
    required String? provider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initiatePayment, [], {
              #orderId: orderId,
              #provider: provider,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>?> getTrackingInfo(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackingInfo, [orderId]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);
}

/// A class which mocks [OrdersLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersLocalDataSource extends _i1.Mock
    implements _i8.OrdersLocalDataSource {
  MockOrdersLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPreferences),
            returnValue: _FakeSharedPreferences_2(
              this,
              Invocation.getter(#sharedPreferences),
            ),
          )
          as _i4.SharedPreferences);

  @override
  _i6.Future<void> cacheOrders(List<_i3.OrderModel>? orders) =>
      (super.noSuchMethod(
            Invocation.method(#cacheOrders, [orders]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cacheOrder(_i3.OrderModel? order) =>
      (super.noSuchMethod(
            Invocation.method(#cacheOrder, [order]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i3.OrderModel? getCachedOrder(int? orderId) =>
      (super.noSuchMethod(Invocation.method(#getCachedOrder, [orderId]))
          as _i3.OrderModel?);

  @override
  _i6.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
