// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/products/domain/usecases/products_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:drpharma_client/core/errors/failures.dart' as _i5;
import 'package:drpharma_client/features/products/domain/entities/product_entity.dart'
    as _i6;
import 'package:drpharma_client/features/products/domain/repositories/products_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i3.ProductsRepository {
  MockProductsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>> getProducts({
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #page: page,
              #perPage: perPage,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ProductEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ProductEntity>>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #page: page,
                      #perPage: perPage,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>> searchProducts({
    required String? query,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [], {
              #query: query,
              #page: page,
              #perPage: perPage,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ProductEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ProductEntity>>(
                    this,
                    Invocation.method(#searchProducts, [], {
                      #query: query,
                      #page: page,
                      #perPage: perPage,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProductEntity>> getProductDetails(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductDetails, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ProductEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ProductEntity>(
                    this,
                    Invocation.method(#getProductDetails, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ProductEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>
  getProductsByPharmacy({
    required int? pharmacyId,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByPharmacy, [], {
              #pharmacyId: pharmacyId,
              #page: page,
              #perPage: perPage,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ProductEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ProductEntity>>(
                    this,
                    Invocation.method(#getProductsByPharmacy, [], {
                      #pharmacyId: pharmacyId,
                      #page: page,
                      #perPage: perPage,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>
  getProductsByCategory({
    required String? category,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [], {
              #category: category,
              #page: page,
              #perPage: perPage,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ProductEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ProductEntity>>(
                    this,
                    Invocation.method(#getProductsByCategory, [], {
                      #category: category,
                      #page: page,
                      #perPage: perPage,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>);
}
