// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/auth/presentation/pages/login_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:drpharma_client/core/errors/failures.dart' as _i5;
import 'package:drpharma_client/core/services/notification_service.dart'
    as _i12;
import 'package:drpharma_client/features/auth/domain/entities/auth_response_entity.dart'
    as _i6;
import 'package:drpharma_client/features/auth/domain/entities/user_entity.dart'
    as _i7;
import 'package:drpharma_client/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:drpharma_client/features/auth/domain/usecases/get_current_user_usecase.dart'
    as _i11;
import 'package:drpharma_client/features/auth/domain/usecases/login_usecase.dart'
    as _i8;
import 'package:drpharma_client/features/auth/domain/usecases/logout_usecase.dart'
    as _i10;
import 'package:drpharma_client/features/auth/domain/usecases/register_usecase.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_1 extends _i1.SmartFake
    implements _i3.AuthRepository {
  _FakeAuthRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.AuthResponseEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.AuthResponseEntity>(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>> register({
    required String? name,
    required String? email,
    required String? phone,
    required String? password,
    String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #phone: phone,
              #password: password,
              #address: address,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.AuthResponseEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.AuthResponseEntity>(
                    this,
                    Invocation.method(#register, [], {
                      #name: name,
                      #email: email,
                      #phone: phone,
                      #password: password,
                      #address: address,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.UserEntity>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.UserEntity>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.UserEntity>>);

  @override
  _i4.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updatePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updatePassword, [], {
                  #currentPassword: currentPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>> verifyOtp({
    required String? identifier,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {
              #identifier: identifier,
              #otp: otp,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.AuthResponseEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.AuthResponseEntity>(
                    this,
                    Invocation.method(#verifyOtp, [], {
                      #identifier: identifier,
                      #otp: otp,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>>
  verifyFirebaseOtp({required String? phone, required String? firebaseUid}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyFirebaseOtp, [], {
              #phone: phone,
              #firebaseUid: firebaseUid,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.AuthResponseEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.AuthResponseEntity>(
                    this,
                    Invocation.method(#verifyFirebaseOtp, [], {
                      #phone: phone,
                      #firebaseUid: firebaseUid,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> resendOtp({
    required String? identifier,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resendOtp, [], {#identifier: identifier}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#resendOtp, [], {
                      #identifier: identifier,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> forgotPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [], {#email: email}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#forgotPassword, [], {#email: email}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i8.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.AuthRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>> call({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #password: password}),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.AuthResponseEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.AuthResponseEntity>(
                    this,
                    Invocation.method(#call, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i9.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.AuthRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>> call({
    required String? name,
    required String? email,
    required String? phone,
    required String? password,
    required String? passwordConfirmation,
    String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #name: name,
              #email: email,
              #phone: phone,
              #password: password,
              #passwordConfirmation: passwordConfirmation,
              #address: address,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.AuthResponseEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.AuthResponseEntity>(
                    this,
                    Invocation.method(#call, [], {
                      #name: name,
                      #email: email,
                      #phone: phone,
                      #password: password,
                      #passwordConfirmation: passwordConfirmation,
                      #address: address,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponseEntity>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i10.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.AuthRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i11.GetCurrentUserUseCase {
  MockGetCurrentUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.AuthRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.UserEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.UserEntity>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.UserEntity>>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i12.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#initNotifications, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendTokenToBackend(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#sendTokenToBackend, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
