// Mocks generated by Mockito 5.4.6 from annotations
// in drpharma_client/test/features/prescriptions/data/repositories/prescriptions_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:drpharma_client/features/prescriptions/data/datasources/prescriptions_remote_datasource.dart'
    as _i2;
import 'package:image_picker/image_picker.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PrescriptionsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrescriptionsRemoteDataSource extends _i1.Mock
    implements _i2.PrescriptionsRemoteDataSource {
  MockPrescriptionsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> uploadPrescription({
    required List<_i4.XFile>? images,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPrescription, [], {
              #images: images,
              #notes: notes,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getPrescriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getPrescriptions, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> getPrescriptionDetails(
    int? prescriptionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPrescriptionDetails, [prescriptionId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> payPrescription(
    int? prescriptionId,
    String? paymentMethod,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#payPrescription, [
              prescriptionId,
              paymentMethod,
            ]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
