// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrhkxUPnykyttiQuUJ1vgP2c4nOe4k3L8',
    appId: '1:866711466162:web:7b061a37e651dea8e859ab',
    messagingSenderId: '866711466162',
    projectId: 'drpharma-f9213',
    authDomain: 'drpharma-f9213.firebaseapp.com',
    storageBucket: 'drpharma-f9213.firebasestorage.app',
    measurementId: 'G-5DRRS3L1TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9KW9rmRqy2LBGOn7Ksa121BQSQqaORM4',
    appId: '1:866711466162:android:0940fa76b5222ccbe859ab',
    messagingSenderId: '866711466162',
    projectId: 'drpharma-f9213',
    storageBucket: 'drpharma-f9213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKeZTluhkiDzaY0ObGQ2kgaRrPl53tQ8I',
    appId: '1:866711466162:ios:b22b0a84f65a4932e859ab',
    messagingSenderId: '866711466162',
    projectId: 'drpharma-f9213',
    storageBucket: 'drpharma-f9213.firebasestorage.app',
    iosBundleId: 'com.drpharma.pharmacyFlutter',
  );
}
